# Generated by Django 2.2.24 on 2021-10-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210629_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='desc',
            new_name='опис',
        ),
    ]
