# Generated by Django 2.2.24 on 2021-10-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20211015_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='опис',
            new_name='desc',
        ),
    ]
