# Generated by Django 3.1.6 on 2021-11-09 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20211015_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks_of_user',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
